spring.application.name=knitly-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/knitly
spring.datasource.username=knitly
spring.datasource.password=knitly

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
